env:
  TERM: xterm-256color
  
# ensuring bold fonts are clearer
draw_bold_text_with_bright_colors: false

# window configuration
window:
  decorations: none
  startup_mode: Maximized
# font configurations
font:
  normal:
    # use $ fc-match <name of font> -s to find the right name
    family: Iosevka

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

scrolling:
  history: 10000

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true
  
cursor:
  style:
    shape: Block 
    
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

import:
  - ~/.config/alacritty/themes/dracula.yml 

