font:
  normal:
  # use $ fc-match <name of font> -s to find the right name
    family: CaskaydiaCove NF
    
selection:
  save_to_clipboard: true
  
mouse_bindings:
  - { mouse: Right, action: PasteSelection }
  
scrolling:
  history: 10000
  
cursor:
  style:
    shape: Block 

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

# Base16 Gruvbox dark, hard 256 - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd5c4a1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d2021'
    cursor: '0xd5c4a1'

  # Normal colors
  normal:
    black:   '0x1d2021'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

  # Bright colors
  bright:
    black:   '0x665c54'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xfbf1c7'

  indexed_colors:
    - { index: 16, color: '0xfe8019' }
    - { index: 17, color: '0xd65d0e' }
    - { index: 18, color: '0x3c3836' }
    - { index: 19, color: '0x504945' }
    - { index: 20, color: '0xbdae93' }
    - { index: 21, color: '0xebdbb2' }

