env:
  TERM: xterm-256color
  
# ensuring bold fonts are clearer
draw_bold_text_with_bright_colors: false

# window configuration
window:
  decorations: none
  startup_mode: Maximized
# font configurations
font:
  normal:
    # use $ fc-match <name of font> -s to find the right name
    family: Iosevka

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

scrolling:
  history: 10000

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true
  
cursor:
  style:
    shape: Block 
    
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

# Colors (Night Owl)
colors:
   # Default colors
  primary:
    background: '#011627'
    foreground: '#d6deeb'

  cursor:
    text: '#011627'
    cursor: '#d6deeb'

  selection:
    background: '#1b90dd'

   # Normal colors
  normal:
    black:   '#011627'
    red:     '#ef5350'
    green:   '#22da6e'
    yellow:  '#c5e478'
    blue:    '#82aaff'
    magenta: '#c792ea'
    cyan:    '#21c7a8'
    white:   '#ffffff'

   # Bright colors
  bright:
    black:   '#575656'
    red:     '#ef5350'
    green:   '#22da6e'
    yellow:  '#ffeb95'
    blue:    '#82aaff'
    magenta: '#c792ea'
    cyan:    '#7fdbca'
    white:   '#ffffff'

